In [1]:
import pandas as pd 
import numpy as np
import math

In [2]:
df=pd.read_csv("~/Downloads/train.csv")
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

# Understanding the data

In [3]:
df.info

<bound method DataFrame.info of         Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg
1        2          20       RL         80.0     9600   Pave   NaN      Reg
2        3          60       RL         68.0    11250   Pave   NaN      IR1
3        4          70       RL         60.0     9550   Pave   NaN      IR1
4        5          60       RL         84.0    14260   Pave   NaN      IR1
...    ...         ...      ...          ...      ...    ...   ...      ...
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
...          ...       ...  ...      ...    ...    ...         ...     ...
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0

     MoSold YrSold  SaleType  SaleCondition  SalePrice
0         2   2008        WD         Normal     208500
1         5   2007        WD         Normal     181500
2         9   2008        WD         Normal     223500
3         2   2006        WD        Abnorml     140000
4        12   2008        WD         Normal     250000
...     ...    ...       ...            ...        ...
1455      8   2007        WD         Normal     175000
1456      2   2010        WD         Normal     210000
1457      5   2010        WD         Normal     266500
1458      4   2010        WD         Normal     142125
1459      6   2008        WD         Normal     147500

[1460 rows x 81 columns]>

In [4]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [5]:
df.isna().sum()
# checking the number of missed values

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

# Droping features with high number of nan values

Alley
PoolQC
Fence
MiscFeature

In [7]:
# df.drop(["Alley","FireplaceQu","PoolQC","Fence","MiscFeature"], axis=1, inplace=True)

In [8]:
mean=df.mean()
df.fillna(mean,inplace=True)

In [9]:
df["BsmtHalfBath"].unique()

array([0, 1, 2])

# checking for outliers and replacing them with mean value of the features

In [10]:
numerical_columns = [column for column in df.columns if df[column].dtype==int and len(df[column].unique()<11)]
numerical_columns=numerical_columns[:-1].copy()

In [25]:
def outlier_detection(column, df):
    outlier=[]
    for x in  df[column]:
        z=np.divide(x-np.mean(df[column]),np.std(df[column]))
        if z > 3:
            outlier.append(x)
            df[column].replace(x,math.ceil(np.mean(df[column])),inplace=True)
    print(column, outlier)     
    

for column in numerical_columns:
    outlier_detection(column, df)

Id []
MSSubClass []
LotArea [21000, 21453, 31770, 22950, 25419, 20431, 22420, 21750, 21872, 21780, 25095, 20896, 21535, 26178, 21695, 21384, 21286, 21750, 20781, 20544, 19690]
OverallQual []
OverallCond []
YearBuilt []
YearRemodAdd []
BsmtFinSF1 [1810, 1767, 1721]
BsmtFinSF2 [486, 491, 506, 362, 169, 181, 215, 208, 441, 184, 279, 306, 180, 228, 175, 264, 147, 232, 380, 294, 258, 121, 180, 344, 210, 311, 165, 279, 180, 174, 139, 202, 123, 219, 147, 182, 132, 336, 287, 180, 180, 119, 182, 117, 239, 127, 128, 377, 345, 324, 93, 294, 149, 193, 117, 273, 64, 230, 106, 240, 287, 177, 108, 211, 168, 96, 144, 81, 68, 173, 105, 110, 163]
BsmtUnfSF [1869, 1836]
TotalBsmtSF [2223]
1stFlrSF [2207, 2223, 2259, 2234, 2217, 2196]
2ndFlrSF []
LowQualFinSF [6, 6, 6, 5, 5, 5, 5, 6, 53, 3, 3, 2, 2, 2, 1, 1, 1, 1]
GrLivArea [2945, 2978, 2872, 2898, 2868, 2872]
BsmtFullBath []
BsmtHalfBath [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
FullBath []
HalfBath []
BedroomAbvGr []
KitchenAbvGr [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
TotRmsAbvGrd []
Fireplaces []
GarageCars []
GarageArea []
WoodDeckSF [409, 441, 414, 426, 416, 403, 418, 421, 404, 402]
OpenPorchSF [204, 213, 199, 205, 228, 238, 198, 208, 228, 184, 195, 214, 231, 192, 187, 176, 182, 172, 204, 174, 170, 188, 192, 191, 189, 169, 185, 200, 180, 192, 198, 184, 166, 170, 169]
EnclosedPorch [87, 172, 102, 144, 64, 77, 144, 144, 140, 183, 60, 120, 77, 52, 144, 108, 177, 91, 130, 169, 105, 120, 80, 115, 144, 84, 148, 120, 136, 102, 54, 39, 36, 40, 67, 90, 120, 56, 129, 40, 98, 143, 70, 134, 120, 68, 34, 20, 32, 20, 48, 94, 108, 22, 19, 80, 115, 21, 17, 102, 18, 84, 15, 81, 13, 42, 20, 50, 13, 17, 16, 17, 21]
3SsnPorch [4, 4, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 3, 2, 23, 3, 1, 1, 1, 1, 1, 1]
ScreenPorch [99, 130, 142, 154, 153, 142, 128, 140, 122, 95, 60, 15, 15, 14, 63, 8, 10, 53, 9, 9, 9, 15, 12, 12, 6, 5, 5, 10, 14, 8, 5, 13, 14, 7, 5, 10]
PoolArea [3, 3, 2, 2, 2, 1, 1]
MiscVal [700, 350, 700, 500, 400, 700, 480, 400, 400, 450, 450, 500, 450, 700, 400, 800, 480, 400, 500, 500, 400, 450, 500, 500, 400, 500, 400, 400, 620, 400, 560, 500, 700, 23, 400, 22, 17, 15, 32, 14]
MoSold []
YrSold []

In [24]:
# df["KitchenAbvGr"].unique()

array([1, 2, 0])

In [21]:
df.isna().sum() 
# confirming all the outliers are gone

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 81, dtype: int64

# converting categorical features to dummy variables

In [14]:
categorical_columns = [column for column in df.columns if df[column].dtype=="object"]
categorical_columns

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [30]:
df_new=pd.get_dummies(data=df,columns= categorical_columns,dummy_na=True)

In [31]:
df_new

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_Oth,SaleType_WD,SaleType_nan,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,SaleCondition_nan
0,1,60,65.0,8450.0,7,5,2003,2003,196.0,706.0,...,0,1,0,0,0,0,0,1,0,0
1,2,20,80.0,9600.0,6,8,1976,1976,0.0,978.0,...,0,1,0,0,0,0,0,1,0,0
2,3,60,68.0,11250.0,7,5,2001,2002,162.0,486.0,...,0,1,0,0,0,0,0,1,0,0
3,4,70,60.0,9550.0,7,5,1915,1970,0.0,216.0,...,0,1,0,1,0,0,0,0,0,0
4,5,60,84.0,14260.0,8,5,2000,2000,350.0,655.0,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917.0,6,5,1999,2000,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
1456,1457,20,85.0,13175.0,6,6,1978,1988,119.0,790.0,...,0,1,0,0,0,0,0,1,0,0
1457,1458,70,66.0,9042.0,7,6,1941,2006,0.0,275.0,...,0,1,0,0,0,0,0,1,0,0
1458,1459,20,68.0,9717.0,5,6,1950,1996,0.0,49.0,...,0,1,0,0,0,0,0,1,0,0
1459,1460,20,75.0,9937.0,5,6,1965,1965,0.0,830.0,...,0,1,0,0,0,0,0,1,0,0

# preparing the data for modeling

In [17]:
# spliting the data into dependent and indepent variable
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [18]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X)
# scaling the data

ValueError: could not convert string to float: 'RL'

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca=PCA(70)
X_pca=pca.fit_transform(X)

In [ ]:
pca.explained_variance_ratio_